import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { AppProviders } from "./providers";
import App from "next/app";
import Navbar from "@/components/Navbar";
// const iconPath = "@/public/ShadyT.svg";
var sessionId = "";
if (typeof window !== "undefined") {
  var sessionID = fetch("/api/assistants/threads/[threadId]/run", {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });
}
const logo = "/shadyt.png";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trivia",
  description: "Generated by create next app",
  icons: {
    icon: "/shadyt.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const sessionId = sessionID;

  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProviders>
          <Navbar />
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
